### PR TITLE
Remove unwanted metadata

### LINKED ISSUE #945: JSON incorrectly checking parts where prose has added blank values for image files
Hello there
Still having a significant problem with the images at http://chroma.space/ as referenced here > https://github.com/prose/prose/issues/903#issuecomment-160321862 

When I update the written content of a page using prose.io "prose puts empty strings where it didn't find metadata before" @weatherbrow >> "The problem is caused by JSON incorrectly checking parts where prose has added blank values for image files." & the effect is that the images disappear...

The workaround was editing out random unwanted values in Github instead of prose.io. But this seems to cripple the CSS and default the page to HTML - see current Now page for example >> http://chroma.space/now/

Is there a better solution? About to start some serious website work and this problem throws a huge spanner in the works. 

thanks
Kate

### PR DESCRIPTION
**Pull request by dereklieu**
1. If a metadata form value is not set, and there is no default value, meta forms should* return an empty string `""`.
2. Instead of including the empty string meta value in frontmatter, Prose will now just not include that property.
3. Exceptions are `title` and `published`.

*Textareas forms are another exception, since reading the values are abstracted in CodeMirror and js-yaml code, `"null"` and `"false"` both register as empty strings and thus will not be included. If for some reason you need to set a meta form to `"false"` or `false`, use a text form.

Would close #945

### CODE REVIEW

**Comment by budparr** [comment]
does that mean if the key already existed, but had no value, it would be deleted? That doesn't seem good to me, if I'm understanding.

**Comment by dereklieu** [comment]
@budparr If you had the default set in `_config.yml` you would still see the form element in the metadata, but if you left that form blank the key just wouldn't appear in the frontmatter. But the form would still be there each time, so if you went back and added a value later then it would appear again.

**Comment by dereklieu** [comment]
@budparr is that how you understood it?

**Comment by budparr** [comment]
That's what I was not understanding. Sounds good.
> so if you went back and added a value later then it would appear again

**Pull request merged**
