### PR TITLE
js-yaml to current version

### PR DESCRIPTION
**Pull request by gesa**
The major issue this resolves is proper yaml multi-line textarea fields. When filling out a textarea with this content:

**Before:**
```yaml
text_area_test: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.\n\nUt enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore\n\neu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
```

**After:**
```yaml
petition_copy: >-
  Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.

  Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore

  eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
```

### CODE REVIEW

**Comment by dereklieu** [comment]
@gesa awesome, this is definitely a marked improvement.

@dhcole @mikemorris @tristen do you remember why we're using a fork of js-yaml instead of the main repo? Don't know the full extent of this module in the codebase and want to make sure I'm not missing anything.

**Comment by dhcole** [comment]
I think it was because js-yml and Jekyll handled booleans differently, like
`false != "false"` in js-yml but they were `==` in Jekyll. This may be
outdated now though.

**Comment by gesa** [comment]
I did a good bit of experimental rebasing on the fork (lol that was like 4 hours I'll never get back 😂😂) as well as testing—via the test suite and QA—both a rebased fork and the original package. I won't lie: ultimately was only about halfway confident i fully understood why the package was forked in the first place. But everything worked great on the latest version of nodeca/js-yaml so I decided to go for it.

**Comment by dereklieu** [comment]
+1 I'm going to do some testing tomorrow and will merge if I don't come across anything.

**Comment by gesa** [comment]
Any movement on this PR?

**Comment by dereklieu** [comment]
@gesa My bad, going to get to it this weekend.

**Comment by dereklieu** [comment]
As far as wrapping booleans in quotes the behavior is the same according to #969, aside from the newer version wrapping in single quotes instead of double, which shouldn't impact the ui in any way. Thanks @gesa

**Pull request merged**
