### PR TITLE
Metadata fixes

### PR DESCRIPTION
**Pull request by dereklieu**
Fixes a number of issues relating to saving and loading metadata from liquid tags.

Includes a major refactor of `app/views/metadata.js`. A big part of this refactor is pushing out the logic of creating, setting, and getting values from form elements into separate views, which are now located in `app/views/meta/`.

Also substantially improves test coverage for the metadata editor and associated form elements. Right now the tests are failing because button form elements I found to be broken, and this fix does not include that (yet) - see #859.

This should address the following tickets:
#836 
#766 
#623 
#582 

Because this is a pretty big refactor, I would love for people to pull this down and test against their own prose configurations, as I continue to test this in the coming days. Please post any bug findings here.

cc @mikemorris @tristen @anandthakker @phillipadsmith @dhcole

### CODE REVIEW

**Comment by phillipadsmith** [comment]
@dereklieu Looking now...

**Comment by phillipadsmith** [comment]
@dereklieu I'm still getting the same (I think?) test failures; not sure if that's an issue for this PR?

Anyway... moving right along... :)

prose-test-failures-august-8-15

**Comment by phillipadsmith** [comment]
Doh, I clearly can't read a PR:

>  Also substantially improves test coverage for the metadata editor and associated form elements. Right now the tests are failing because button form elements I found to be broken, and this fix does not include that (yet) - see #859.

**Comment by phillipadsmith** [comment]
Howdy, I've tested this PR against this issues:
#836 
#766 
#623 
#582
... and they all appear to be fixed.

**Comment by dereklieu** [comment]
@phillipadsmith thanks for checking this out!

I wouldn't mind leaving this open for another day or two, especially since I'd like to fix the button issue before merging as well.

**Comment by phillipadsmith** [comment]
@dereklieu :+1:

**Comment by dereklieu** [comment]
I've fixed the button element bug and unearthed one or two others meanwhile. Hurray for tests.

**Comment by dereklieu** [comment]
Should also fix #635

**Pull request merged**
