### PR TITLE
Tests for metadata name collision, textarea saving

### PR DESCRIPTION
**Pull request by dereklieu**
I've written an initial set of tests for `/app/views/metadata.js`. Some notes on this file:

To facilitate testing, I created a fake model that mocks `/app/models/file.js`, and a fake view that mocks `/app/views/file.js`. These are both dependencies that I don't want to include directly. 

I'm using jQuery to trigger change events. Before each test, I append a `<div id="#meta"></div>` to the tail end of the test page and set this as the view's `el` property. This `div` gets removed after each test runs.

This is not an exhaustive test file, but currently two of them are failing. One shows that you can break the view by including a meta element which forces a name collision on `this`. The other shows that textarea changes aren't being saved to the model. If we're able to merge, I can start to work on getting these tests to pass.

Would love feedback!

### CODE REVIEW

**Comment by dereklieu** [comment]
@anandthakker @mikemorris Had a chance to refactor this test spec to use the mock system that we set up. Same tests, same ones failing, but a lot less verbose than before.

This also includes a new mock for `views/file.js` which you can see [here](https://github.com/dereklieu/prose/commit/f24d7677edae89e8b301085c69039d307b3ff000).

**Comment by mikemorris** [comment]
:+1: @dereklieu, deferring to @anandthakker here for a final opinion

**Comment by anandthakker** [comment]
@dereklieu LGTM!

**Comment by dereklieu** [comment]
Thanks all! I'm going to move on to fixing these now.

**Comment by crawfordcomeaux** [comment]
I think the test for #766 may need some rethinking. 

1. It's comparing the rendered view to an undefined variable `view` that seems to have been left hanging after rewriting the tests for the new mocks. 

2. Rendering the view adds some objects to the view that weren't in it before. Wouldn't that lead .deep.equal to fail even if text area metadata isn't overwritten?

**Comment by dereklieu** [comment]
@crawfordcomeaux thanks, you're right, this test is flawed for the reasons you've outlined.

A better test might check to see if `metadataEditor.view` has properties that you'd expect the file view to have, such as a `branch` property.

**Pull request merged**
