### PR TITLE
Allow specifying content for new files via url query params

### PR DESCRIPTION
**Pull request by agius**
This turned out to be easier than I thought. Hopefully will work with proposed model refactor as well.

Closes [issue 435](https://github.com/prose/prose/issues/435)

### CODE REVIEW

**Comment by patcon** [comment]
Have reviewed a bunch of issues looking for this, and I feel this is the best place to drop the ask:

Is there any alternative way to set default for "content" on the "new file" page that prose shows? Seems hardcoded right now, if I'm not mistaken. Any guidance appreciated :)

**Comment by dereklieu** [comment]
I think a more robust direction would be setting the default value via prose config.yml file. That config data is made available at various parts of the codebase, and this could easily be documented.

**Comment by sheldonhull** [comment]
any confirmation if this is supported in anyway yet? I don't see a clear no, but I can't find any option mentioned to set default text for content

**Comment by dereklieu** [comment]
Sorry, have not had time to work on this, and this is not a currently supported feature.

**Pull request closed without merging**
