### PR TITLE
Enhanced localization for Russian

### PR DESCRIPTION
**Pull request by denpatin**

### CODE REVIEW

**Comment by mikemorris** [comment]
Thanks for the updates @denpatin! [We're using Transifex to manage our translations](https://github.com/prose/prose/blob/master/CONTRIBUTING.md#translating) though, so these files are auto-generated - can you submit your changes to the [Prose project on Transifex](https://www.transifex.com/projects/p/prose/) instead?

**Comment by denpatin** [comment]
@mikemorris I already got that :) Three days ago I have requested to join the translation team on Transifex but there is still no answer...

**Comment by tristen** [comment]
@denpatin - just added you to the team!

**Comment by mikemorris** [comment]
Got you added now @denpatin :smile:

**Comment by denpatin** [comment]
@tristen Yeah, I see. Thank you!

**Comment by denpatin** [comment]
@tristen @mikemorris Have uploaded there my version of the translation. What's to be done next? Will there be some review?

**Pull request closed without merging**
