### PR TITLE
Create Dockerfile

### PR DESCRIPTION
**Pull request by dalareo**

### CODE REVIEW

**Comment by dereklieu** [comment]
@dalareo just curious, what's your use case here? Are you doing automated deployments of prose? 

I can see the utility of having this, but I think there should be a note about how to use it in [contributing.md](https://github.com/prose/prose/blob/master/CONTRIBUTING.md)

**Comment by dalareo** [comment]
I am designing a ContainerAsAService platform use case devoted to education institutions. Github workflow is the right one to create content collaboratively and open. Prose is the software candidate. You can check also a related-project: https://github.com/dalareo/TellGit

**Comment by Thetoxicarcade** [comment]
Should this one be closed if you merged another docker file?

**Comment by dereklieu** [comment]
There is no dockerfile that's been merged (that's on a fork) but this should be straightforward for anyone who wants to dockerize Prose to do themselves. Closing.

**Comment by Thetoxicarcade** [comment]
awwwww :(

**Pull request closed without merging**
