### PR TITLE
added language direction for arabic. #645

### PR DESCRIPTION
**Pull request by tareefdev**
I find another way to support RTL direction, as `sytle-rtl.css` contains the needed work for the interface, I just added a class to make editor direction is RTL too, and toggle it on for both Arabic and Hebrew.

### CODE REVIEW

**Comment by nikonikoniko** [comment]
also for #775

**Comment by dy** [comment]
Good candidate @dereklieu

**Review by babbitt — CHANGES_REQUESTED** [review]
LGTM once typo is fixed. Tested changes locally using rtl language.  

We should adjust the hebrew code to `he_IL` to keep up with Transifex changes but otherwise ready to merg

The selection behavior still isn't perfect but it's a start. Better to have this than our current implementation (none)

**Comment by babbitt** [comment]
Because @tareefdev has deleted their repo we can't change / expect changes so going to merge this into a rtl branch then follow up with changes requested before merging.

**Comment by babbitt** [comment]
@tareefdev Since your branch is deleted and now out of date with master, I'm unable to merge your changes. That being said, we'd love to be able to make sure you get the credit you deserve. If you can please open a new commit with the same changes (+ the requested ones) we'll get this merged in :)

For those looking for the functionality. I'll let this simmer for a week and if Tareef doesn't get back to us by then I'll replicate the changes myself.

**Pull request closed without merging**
