### PR TITLE
404 Authorize button & Repository Scope

### PR DESCRIPTION
**Pull request by dhcole**
Offer unauthenticated users the option to authorize to with GitHub on 404 errors. Redirects back to the original file after successful authentication.

screenshot 2015-02-12 22 19 27

When users try to access a post in a private repository without authorizing first, GitHub's API returns a 404. This gives the user the option to authenticate and return to that page.

### CODE REVIEW

**Comment by dhcole** [comment]
Added in a collapsable select box to set the repository scope. The section persists in a cookie for future log-in attempts. Also, the authenticate button from the nav now redirects the user to the page on which they started.

screenshot 2015-02-13 01 05 05

screenshot 2015-02-13 01 05 26

Resolves #126

**Comment by mikemorris** [comment]
Welcome back @dhcole! UX on this looks great and solves that issue elegantly, I'm :+1: on merge.

**Comment by dereklieu** [comment]
Like this solution as well. +1

**Comment by mbland** [comment]
+1

**Comment by dhcole** [comment]
Thanks @mikemorris and @dereklieu for the review!

**Pull request merged**
