### PR TITLE
Re-implement CURRENT_DATETIME replacement in metadata

### LINKED ISSUE #277: Feature request: ability to specify date=NOW in metadata settings
``` yaml
#prose.io settings
prose:
  rooturl: "source"
  metadata:
    "source/_posts": |
      layout: post
      title: "Title"
      date: 2012-12-22 14:07
      comments: true
      categories: 
      published: true
```

I would like to be able to specify `date: CURRENT` or something and have this field autogenerated on document creation. or just point me on place to implement this

### PR DESCRIPTION
**Pull request by holic**
Closes #277

### CODE REVIEW

**Comment by parkr** [comment]
This looks fine to me. Would you mind adding a test for these 2 cases?

**Comment by holic** [comment]
Can do. Any idea why master is currently failing tests?

**Comment by parkr** [comment]
> Can do. Any idea why master is currently failing tests?

I'm really not sure. The build errors out because the gulp task doesn't end which is weird... 

2 failing tests are:

```text
1) textarea names do not collide with view methods
2) saves changes to model on textarea element change
```

**Comment by dereklieu** [comment]
Hey, sorry for the confusion regarding those tests. They currently fail because they show where Prose is malfunctioning in regards to the meta data elements. I haven't had a chance to make a pull request to fix those parts yet.

**Comment by parkr** [comment]
> they show where Prose is malfunctioning in regards to the meta data elements

Whaddaya mean? How much time do you need for a PR?

**Comment by dereklieu** [comment]
@parkr it's taken me a while, this is true. If you'd like to contribute in this area, the tests show what need to be done.

**Comment by holic** [comment]
I dug around the tests a bit, but couldn't seem to find a test that does something similar that I can use as an example when adding more tests for this specific change. Any hints?

**Comment by dereklieu** [comment]
@holic I PRd a few tests into your branch, I hope it helps. 

Is including seconds too much detail? I like having the offset but I don't know if most people care what second their blog post is created.

**Comment by holic** [comment]
I figured the extra granularity couldn't hurt (and only a few extra characters), but I can certainly remove it if you don't think it's needed.

**Comment by dereklieu** [comment]
@holic if you don't have strong feelings about it, I would recommend leaving seconds out and just going with minutes + offset, since I think that will simplify it for people who won't be editing this metadata as a form element. I think it's good to merge after that.

**Comment by holic** [comment]
@dereklieu Done.

**Comment by jhabdas** [comment]
Nice!

**Pull request merged**
